cmake_minimum_required(VERSION 3.22.1)
project("soreal")
set(CMAKE_CXX_STANDARD 20)
set(CMAKE_CXX_STANDARD_REQUIRED ON)
add_library(soreal SHARED engine/SorealEngine.cpp platform/AndroidPlatform.cpp render/Renderer.cpp render/VulkanCapabilities.cpp)
target_include_directories(soreal PRIVATE ${CMAKE_CURRENT_SOURCE_DIR})
find_library(log-lib log)
find_library(android-lib android)
find_library(gles-lib GLESv3)
find_library(vulkan-lib vulkan)
target_link_libraries(soreal ${log-lib} ${android-lib} ${gles-lib} ${vulkan-lib})
